[package]
org = "ballerina"
name = "constraint_validation_tests"
version = "0.8.1"

[[dependency]]
org = "ballerina"
name = "csv_commons"
repository = "local"
version = "0.8.1"

[platform.java21]
graalvmCompatible = true

[build-options]
graalvmBuildOptions = "-H:+IncludeAllLocales"
