[package]
org = "ballerina"
name = "union_type_tests"
version = "0.10.0"

[[dependency]]
org = "ballerina"
name = "csv_commons"
repository = "local"
version = "0.10.0"

[platform.java21]
graalvmCompatible = true

[build-options]
graalvmBuildOptions = "-H:+IncludeAllLocales"
