[package]
org = "ballerina"
name = "data.csv"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["csv"]
repository = "https://github.com/ballerina-platform/module-ballerina-data.csv"
license = ["Apache-2.0"]
distribution = "2201.12.0"
export = ["data.csv"]

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "data.csv-native"
version = "@toml.version@"
path = "../native/build/libs/data.csv-native-@project.version@.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "@constraint.version@"
path = "./lib/constraint-native-@stdlib.constraintnative.version@.jar"
