[package]
org = "ballerina"
name = "fail_safe_mechanism"
version = "0.9.0"

[[dependency]]
org = "ballerina"
name = "csv_commons"
repository = "local"
version = "0.9.0"

[platform.java21]
graalvmCompatible = true

[build-options]
graalvmBuildOptions = "-H:+IncludeAllLocales"
