[package]
org = "ballerina"
name = "data.csv"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["csv"]
repository = "https://github.com/ballerina-platform/module-ballerina-data.csv"
license = ["Apache-2.0"]
distribution = "2201.9.0"
export = ["data.csv"]

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "data.csv-native"
version = "0.1.0"
path = "../native/build/libs/data.csv-native-0.1.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "@constraint.version@"
path = "./lib/constraint-native-@stdlib.constraintnative.version@.jar"
