[plugin]
id = "data.csv-compiler-plugin"
class = "io.ballerina.lib.data.csvdata.compiler.CsvDataCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/data.csv-compiler-plugin-0.8.1-SNAPSHOT.jar"
